package escholz.greenfield.net.catalog.models

/**
 * This type contains the full details of a specified catalog change request, including the original payload of the
 * createChangeRequest call, processing status and key dates, and resolution details.
 */
data class ChangeRequest(
    /**
     * The unique identifier of this change request. This value was originally generated by the createChangeRequest
     * call and returned in the location code of that call's HTTP response header.
     */
    val changeRequestId: String,

    /**
     * The current processing status of this change request. If the value of this field is APPROVED_WITH_MODIFICATIONS,
     * the change request has been approved with one or more modifications applied by eBay.
     * Check the processResolution.corrections response object for details about the modifications.
     * <p />
     * If the value of this field is REJECTED, the change request has been rejected for violating eBay standards or for conflicting
     * with an existing product record. Check the processResolution.violations response object for details about the
     * rejection.
     * <p />
     * Available values:
     * <p />
     * APPROVED &mdash; Upon review, the change request has been approved as submitted.
     * <p />
     * APPROVED_WITH_MODIFICATIONS &mdash; Upon review, the change request has been approved with one or more
     * corrections applied by eBay. Check the processResolution.corrections response object for details about the
     * modifications.
     * <p />
     * REJECTED &mdash; Upon review, the change request has been rejected for a conflict with an existing catalog
     * product, or for violating eBay standards. Check the processResolution.violations response object for details
     * about the rejection.
     * <p />
     * SUBMITTED &mdash; The change request has been submitted and is being processed.
     * <p />
     * UNDER_EXTENDED_REVIEW &mdash; After one hour of review, the change request is under extended review by eBay.
     * <p />
     * UNDER_REVIEW &mdash; Upon submission/processing, the change request is under review by eBay. This typically
     * takes up to one hour.
     *
     * @see <a href='https://developer.ebay.com/devzone/rest/api-ref/catalog/types/ChangeRequestStatus.html'>eBay API documentation</a>
     */
    val changeRequestStatus: String,

    /**
     * The type of catalog modification being requested by this change request.
     * <p />
     * Available values:
     * <p />
     * PRODUCT_CREATION &mdash; Change request to create a new product
     * <p />
     * PRODUCT_UPDATE &mdash; Change request to update an existing product
     *
     * @see <a href='https://developer.ebay.com/devzone/rest/api-ref/catalog/types/ChangeRequestType.html'>eBay API documentation</a>
     */
    val changeRequestType: String,

    /**
     * The creation date of this change request.
     */
    val creationDate: String,

    /**
     * eBay's estimate of the completion date of this change request.
     */
    val expectedCompletionDate: String,

    /**
     * Returned if the value of changeRequestStatus is one of the following:
     * <p />
     * APPROVED
     * <p />
     * APPROVED_WITH_MODIFICATIONS &mdash; Indicates that the product was created or updated by eBay with certain
     * corrections applied to its attributes or aspects.
     * <p />
     * REJECTED &mdash; Indicates that the suggested product either conflicts with existing products or violates eBay
     * standards. This container provides details of conflicting products, corrections required, or violations that
     * were discovered in this change request
     */
    val processResolution: ProcessResolution,

    /**
     * A text description and explanation of the status indicated by the changeRequestStatus field.
     */
    val processStatusMessage: String,

    /**
     * A text description of why this change request was submitted.
     */
    val reasonForChangeRequest: String,

    /**
     * Returned if the referenceType field is returned in the response. This is the identifier of an object of the type
     * specified by the value of referenceType. For example, if the value of referenceType is INVENTORY_ITEM, this
     * field should contain the seller's SKU for an inventory item.
     */
    val referenceId: String,

    /**
     * Returned if this field was included in the the createChangeRequest call. This specifies the type of eBay object
     * that the seller wants to create or update using the requested change. It applies to objects that are incomplete
     * due to the need for a matching catalog product. Providing a referenceType and a referenceId in a catalog change
     * request enables eBay to automatically apply the resulting new or updated product directly to the specified
     * object without requiring additional action on your part.
     * <p />
     * Available values:
     * <p />
     * INVENTORY_ITEM &mdash; The requested change will support the completion of an inventory item, which you can then
     * use to create an offer.
     * <p />
     * LISTING &mdash; The requested change will support the modification of an active product listing.
     * <p />
     * LISTING_DRAFT &mdash; The requested change will support the completion of an offer, which you can then publish
     * as a product listing.
     *
     * @see <a href='https://developer.ebay.com/devzone/rest/api-ref/catalog/types/ReferenceType.html'>eBay API documentation</a>
     */
    val referenceType: String,

    /**
     * Returned if the value of changeRequestStatus is APPROVED, APPROVED_WITH_MODIFICATIONS, or REJECTED. This is the
     * date that the change request was resolved.
     */
    val resolutionDate: String,

    /**
     * Contains the full details of the suggested product, including information about the product's identifiers,
     * description, product images, categories, and aspects.
     */
    val suggestedProduct: SuggestedProduct
)