package escholz.greenfield.net.catalog

import escholz.greenfield.net.catalog.models.*
import kotlinx.coroutines.Deferred
import retrofit2.Response
import retrofit2.http.*

/**
 * Use the Catalog API to search the eBay catalog for products on which to base a seller's item listing; to retrieve a
 * product record by its eBay product identifier (ePID); to submit a catalog change request to modify an existing
 * product or create a new product; and to manage catalog change requests.
 */
interface CatalogApi {
    // TODO: Add Auth Header
    // TODO: ApiError Handling
    /**
     * Use this call to retrieve the contents of a catalog change request based on its unique identifier,
     * change_request_id. The change_request_id value was originally generated by the createChangeRequest call, and is
     * returned by the getChangeRequests call in the changeRequests.changeRequestId field.
     *
     * @param marketplaceId Use this header to identify the authenticated user's business context. This header is
     * currently limited to EBAY_US, EBAY_AU, EBAY_CA, and EBAY_GB values. If not included with your request, the
     * marketplace value defaults to EBAY_US. Note that it does not indicate a language preference or end-user location.
     * @param language Use this header to specify the natural language in which the authenticated user desires the
     * response.
     * @param changeRequestId The unique identifier of the change request being requested. This value was originally
     * generated by the createChangeRequest call, and is returned by the getChangeRequests call in the
     * changeRequests.changeRequestId field.
     */
    @GET("change_request/{change_request_id}")
    fun getChangeRequest(
        @Header("X-EBAY-C-MARKETPLACE-ID") marketplaceId: String,
        @Header("Accept-Language") language: String,
        @Path("change_request_id") changeRequestId: String
    ): Deferred<Response<ChangeRequest>>

    /**
     * Use this call to search for and retrieve one or more catalog change requests that were submitted by the
     * authenticated user based on their creation date, processing status, reference type or reference ID.
     *
     * @param marketplaceId Use this header to identify the authenticated user's business context. This header is
     * currently limited to EBAY_US, EBAY_AU, EBAY_CA, and EBAY_GB values. If not included with your request, the
     * marketplace value defaults to EBAY_US. Note that it does not indicate a language preference or end-user location.
     * @param language Use this header to specify the natural language in which the authenticated user desires the
     * response.
     * @param filter One or more comma-separated criteria for narrowing down the collection of change requests
     * returned by this call. These criteria correspond to specific fields in the response payload. Multiple filter
     * criteria combine to further restrict the results.
     * <p />
     * The available criteria are as follows:
     * <p />
     * creationDate The time period during which qualifying change requests were created
     * (the changeRequests.creationDate field). In the URI, this is expressed as a starting timestamp, with or without
     * an ending timestamp (in brackets). The timestamps are in ISO 8601 format, which uses the 24-hour Universal
     * Coordinated Time (UTC) clock. For example: creationDate:[2016-02-21T08:25:43.511Z..] identifies orders created
     * on or after the given timestamp.
     * <p />
     * creationDate:[2016-02-21T08:25:43.511Z..2016-04-21T08:25:43.511Z] identifies orders created between the given
     * timestamps, inclusive.
     * <p />
     * changeRequestStatus The degree to which qualifying change requests have been resolved
     * (the changeRequests.changeRequestStatus field). For example: changeRequestStatus:{SUBMITTED} specifies change
     * requests that have been submitted and are being processed.
     * changeRequestStatus:{UNDER_REVIEW|APPROVED_WITH_MODIFICATIONS} specifies change requests that are being
     * reviewed by eBay, and change requests that have been approved, but eBay has made some modifications such as
     * correcting typographic errors. changeRequestStatus:{REJECTED} specifies change requests that have been rejected
     * by eBay because of a violation.
     * <p />
     * referenceId The identifier of an object of the type specified by the value of the referenceType parameter.
     * For example, if the value of referenceType is INVENTORY_ITEM, this field should contain the seller's SKU for an
     * inventory item. If you include this without the referenceType parameter, the filter will apply to objects of any
     * reference type with this reference ID, if specified in the change request. This parameter can take multiple
     * values. For example: referenceId:{234242|675756}
     * <p />
     * referenceType The type of object that a requested catalog change is intended to support, if specified in the
     * change request (the changeRequests.referenceType field). For example: referenceType:{INVENTORY_ITEM} indicates
     * that the requested change will support the completion of an inventory item, which you can then use to create
     * an offer. referenceType:{LISTING} indicates that the requested change will support the modification of an
     * active product listing. referenceType:{LISTING_DRAFT} indicates that the requested change will support the
     * completion of an offer, which you can then publish as a product listing.
     * @param limit The number of change requests to return. This is the result set, a subset of the full collection of
     * change requests that match the filter criteria of this call. Maximum: 200 Default: 50
     * @param offset The first change request to return based on its position in the returned collection of change
     * requests. Use this parameter in conjunction with the limit parameter to control the pagination of the output.
     * For example, if offset is set to 10 and limit is set to 10, the call retrieves change requests 11 thru 20 from
     * the resulting collection of change requests. Note: This feature employs a zero-based list, where the first item
     * in the list has an offset of 0. Default: 0 (zero)
     *
     * @see <a href="https://developer.ebay.com/devzone/rest/api-ref/catalog/types/FilterField.html">FilterField API</a>
     */
    @GET("change_request")
    fun getChangeRequests(
        @Header("X-EBAY-C-MARKETPLACE-ID") marketplaceId: String,
        @Header("Accept-Language") language: String,
        @Query("filter") filter: String,
        @Query("limit") limit: String,
        @Query("offset") offset: String
    ): Deferred<Response<GetChangeRequestsResponse>>

    /**
     * When sellers are unable to identify an eBay catalog product on which to base their item listing, this call
     * enables you to request that eBay update an existing product record or create a new product record that will
     * successfully match the seller's inventory item.
     *
     * @param marketplaceId Use this header to identify the authenticated user's business context. This header is
     * currently limited to EBAY_US, EBAY_AU, EBAY_CA, and EBAY_GB values. If not included with your request, the
     * marketplace value defaults to EBAY_US. Note that it does not indicate a language preference or end-user location.
     * @param language Use this header to specify the natural language in which the authenticated user desires the
     * response.
     * @param body Contains the full details of a specified catalog change request, including the type of request, the
     * reason for a product update request, and the details of the new or updated product being suggested.
     */
    @Headers("Content-type: application/json")
    @POST("change_request")
    fun postChangeRequest(
        @Header("X-EBAY-C-MARKETPLACE-ID") marketplaceId: String,
        @Header("Accept-Language") language: String,
        @Body body: CreateChangeRequestPayload
    ): Deferred<Response<ApiError>>

    /**
     * This call retrieves details of the catalog product identified by the eBay product identifier (ePID) specified in
     * the request. These details include the product's title and description, aspects and their values, associated
     * images, applicable category IDs, and any recognized identifiers that apply to the product. For a new listing,
     * you can use the search call to identify candidate products on which to base the listing, then use the getProduct
     * call to present the full details of those candidate products to the seller to makea a final selection.
     *
     * @param epid The ePID of the product being requested. This value can be discovered by issuing the search call and
     * examining the value of the productSummaries.epid field for the desired returned product summary.
     */
    @GET("product/{epid}")
    fun getProduct(
        @Header("Authorization") bearerToken: String,
        @Path("epid") epid: String
    ): Deferred<Response<Product>>

    /**
     *
     * @param aspectFilter
     * @param categoryIds
     * @param fieldGroups
     * @param query
     * @param gtin
     * @param mpn
     * @param limit
     * @param offset
     */
    @GET("product_summary/search")
    fun findProduct(
        @Query("aspect_filter") aspectFilter: String,
        @Query("category_ids") categoryIds: String,
        @Query("fieldgroups") fieldGroups: String,
        @Query("q") query: String,
        @Query("gtin") gtin: String,
        @Query("mpn") mpn: String,
        @Query("limit") limit: String,
        @Query("offset") offset: String
    ): Deferred<Response<ProductSearchResponse>>

    /**
     *
     */
    @GET("get_product_metadata")
    fun getProductMetadata(
        @Header("X-EBAY-C-MARKETPLACE-ID") marketplaceId: String,
        @Header("Accept-Language") language: String,
        @Query("epid") epid: String,
        @Query("primary_category_id") primaryCategoryId: String,
        @Query("other_applicable_category_ids") otherApplicableCategoryIds: String
    ): Deferred<Response<ProductMetadata>>

    /**
     *
     */
    @GET("get_product_metadata_for_categories")
    fun getProductMetadata(
        @Header("X-EBAY-C-MARKETPLACE-ID") marketplaceId: String,
        @Header("Accept-Language") language: String,
        @Query("primary_category_id") primaryCategoryId: String,
        @Query("other_applicable_category_ids") otherApplicableCategoryIds: String
    ): Deferred<Response<ProductMetadataForCategories>>
}